### ISSUE TITLE
Error compiling Batch.xs: 'LSF_Batch_rsvInfoEnt' has no member named 'rsvUnit'

### ISSUE THREAD

**Issue by ernstki** [IBMSpectrumComputing/lsf-perl-api#2]
Attempting to compile LSF::Batch on an LSF 8.3.0 system results in this error message:

```
Batch.xs: In function 'XS_LSF__Batch__rsvInfoEntPtr_rsvUnit':
Batch.xs:6985: error: 'LSF_Batch_rsvInfoEnt' has no member named 'rsvUnit'
```

The culprit seems to be `Batch.xs` [line 6979](../blob/master/LSF-Batch/Batch.xs#L6979):

```
#if LSF_VERSION >= LSF_XDR_VERSION9_1_3
```

I'm guessing this `#define` won't be present in `<lsf/lsf.h>` on versions of LSF _prior_ to 9.1.3., because on my system, the latest one I have is `LSF_XDR_VERSION8_0_2`.

It may be the case that 8.3.0 is no longer in active support (I don't personally administer our cluster, so I don't know), but it seems like this problem would occur on _any_ LSF installation with a version < 9.1.3.

A pull request to (hopefully) correct the issue is forthcoming.

**Comment by adamsla** [comment]
Okay, being that the pull request is merged, I'll go ahead and close this one.
